---
- name: VyOS Router Congfiguration
  hosts: vyos
  gather_facts: no
  become: yes
  vars:
    admin_password: "YOUR_NEW_PASSWORD"
    wan_ip: "IP/CIDR"
    wan_gateway: "IP"
    lan_ip: "IP/CIDR"
    lan_subnet: "IP/CIDR"
    vrrp_wan_address: "IP/CIDR"
    vrrp_lan_address: "IP/CIRD"

  tasks:
    - name: Enter configuration mode and apply settings
      vyos_config:
        lines:
          # General system setup
          - set system login user vyos authentication plaintext-password {{ admin_password }}
          - set system host-name IndulgenceOfConviction

          # Interface setup
          - set interfaces ethernet eth0 address {{ wan_ip }}
          - set protocols static route 0.0.0.0/0 next-hop {{ wan_gateway }}
          - set interfaces ethernet eth0 description 'WAN'
          - set interfaces ethernet eth1 address {{ lan_ip }}
          - set interfaces ethernet eth1 description 'LAN'

          # NAT
          - set nat source rule 100 outbound-interface name eth0
          - set nat source rule 100 source address {{ lan_subnet }}
          - set nat source rule 100 translation address masquerade

          # Firewall rules
          - set firewall zone WAN member interface eth0
          - set firewall zone LAN member interface eth1
          - set firewall zone LOCAL local-zone

          - set firewall zone WAN default-action drop
          - set firewall zone LAN default-action drop
          - set firewall zone LOCAL default-action drop

          - set firewall ipv4 name LANTOWAN default-action drop
          - set firewall ipv4 name LANTOWAN rule 10 action accept
          - set firewall ipv4 name LANTOWAN rule 10 state new enable
          - set firewall ipv4 name LANTOWAN rule 10 state established enable
          - set firewall ipv4 name LANTOWAN rule 10 state related enable

          - set firewall ipv4 name WANTOLAN default-action drop
          - set firewall ipv4 name WANTOLAN rule 10 action accept
          - set firewall ipv4 name WANTOLAN rule 10 state established
          - set firewall ipv4 name WANTOLAN rule 10 state related
          - set firewall zone LAN from WAN firewall name WANTOLAN

          # DNS
          - set system name-server 1.1.1.1
          - set system name-server 8.8.8.8
          - set service dns forwarding
          - set service dns forwarding allow-from {{ lan_subnet }}
          - set service dns forwarding listen-address 172.16.2.1
          - set service dns forwarding system

          # VRRP
          - set high-availability vrrp group WAN vrid 10
          - set high-availability vrrp group WAN interface eth0
          - set high-availability vrrp group WAN address {{ vrrp_wan_address }}
          - set high-availability vrrp group WAN priority 150
          - set high-availability vrrp group WAN preempt-delay 5

          - set high-availability vrrp group LAN vrid 20
          - set high-availability vrrp group LAN interface eth1
          - set high-availability vrrp group LAN address {{ vrrp_lan_address }}
          - set high-availability vrrp group LAN priority 150
          - set high-availability vrrp group LAN preempt-delay 5

        save: yes