---
- name: VyOS Router Congfiguration
  hosts: vyos_hosts
  gather_facts: no
  become: yes
  vars:
    admin_password: "YOUR_NEW_PASSWORD"
    wan_ip: "IP/CIDR"
    wan_gateway: "IP"
    lan_ip: "IP/CIDR"
    lan_ip_nocidr: "IP"
    lan_subnet: "IP/CIDR"
    dns_address: "IP"
    vrrp_wan_address: "IP/CIDR"
    vrrp_lan_address: "IP/CIDR"

  tasks:
    - name: Enter configuration mode and apply settings
      vyos_config:
        lines:
          # General system setup
          - set system login user vyos authentication plaintext-password {{ admin_password }}
          - set system host-name IndulgenceOfConviction

          # Interface setup
          - set interfaces ethernet eth0 address {{ wan_ip }}
          - set protocols static route 0.0.0.0/0 next-hop {{ wan_gateway }}
          - set interfaces ethernet eth0 description 'WAN'
          - set interfaces ethernet eth1 address {{ lan_ip }}
          - set interfaces ethernet eth1 description 'LAN'

          # NAT
          - set nat source rule 100 outbound-interface name eth0
          - set nat source rule 100 source address {{ lan_subnet }}
          - set nat source rule 100 translation address masquerade

          # DNS
          - set system name-server 1.1.1.1
          - set system name-server 8.8.8.8
          - set service dns forwarding
          - set service dns forwarding allow-from {{ lan_subnet }}
          - set service dns forwarding listen-address {{ dns_address }}
          - set service dns forwarding listen-address {{ lan_ip_nocidr }}
          - set service dns forwarding system

          # Firewall Rules
          - set firewall zone WAN member interface eth0
          - set firewall zone LAN member interface eth1
          - set firewall zone LOCAL local-zone

          - set firewall zone WAN default-action drop
          - set firewall zone LAN default-action drop
          - set firewall zone LOCAL default-action drop

          - set firewall ipv4 name LANTOWAN default-action drop
          - set firewall ipv4 name LANTOWAN rule 10 action accept
          - set firewall ipv4 name LANTOWAN rule 10 state new
          - set firewall ipv4 name LANTOWAN rule 10 state established
          - set firewall ipv4 name LANTOWAN rule 10 state related
          - set firewall zone WAN from LAN firewall name LANTOWAN

          - set firewall ipv4 name WANTOLAN default-action drop
          - set firewall ipv4 name WANTOLAN rule 10 action accept
          - set firewall ipv4 name WANTOLAN rule 10 state established
          - set firewall ipv4 name WANTOLAN rule 10 state related
          - set firewall zone LAN from WAN firewall name WANTOLAN

          - set firewall ipv4 name LOCALTOWAN default-action drop
          - set firewall ipv4 name LOCALTOWAN rule 10 action accept
          - set firewall ipv4 name LOCALTOWAN rule 10 protocol udp
          - set firewall ipv4 name LOCALTOWAN rule 10 destination port 53
          - set firewall ipv4 name LOCALTOWAN rule 20 action accept
          - set firewall ipv4 name LOCALTOWAN rule 20 protocol tcp
          - set firewall ipv4 name LOCALTOWAN rule 20 destination port 53
          - set firewall ipv4 name LOCALTOWAN rule 90 action accept
          - set firewall ipv4 name LOCALTOWAN rule 90 state established
          - set firewall ipv4 name LOCALTOWAN rule 90 state related
          - set firewall zone WAN from LOCAL firewall name LOCALTOWAN

          - set firewall ipv4 name WANTOLOCAL default-action drop
          - set firewall ipv4 name WANTOLOCAL rule 10 action accept
          - set firewall ipv4 name WANTOLOCAL rule 10 state established
          - set firewall ipv4 name WANTOLOCAL rule 10 state related
          - set firewall zone LOCAL from WAN firewall name WANTOLOCAL

          # Firewall Service Rules
          - set firewall ipv4 name LANTOLOCAL default-action drop
          - set firewall ipv4 name LANTOLOCAL rule 10 action accept
          - set firewall ipv4 name LANTOLOCAL rule 10 protocol tcp
          - set firewall ipv4 name LANTOLOCAL rule 10 destination port 22
          - set firewall ipv4 name LANTOLOCAL rule 10 source address 172.16.2.0/24

          - set firewall ipv4 name LANTOLOCAL rule 20 action accept
          - set firewall ipv4 name LANTOLOCAL rule 20 protocol udp
          - set firewall ipv4 name LANTOLOCAL rule 20 destination port 53
          - set firewall ipv4 name LANTOLOCAL rule 20 source address 172.16.2.0/24

          - set firewall ipv4 name LANTOLOCAL rule 21 action accept
          - set firewall ipv4 name LANTOLOCAL rule 21 protocol tcp
          - set firewall ipv4 name LANTOLOCAL rule 21 destination port 53
          - set firewall ipv4 name LANTOLOCAL rule 21 source address 172.16.2.0/24

          - set firewall zone LOCAL from LAN firewall name LANTOLOCAL

          - set firewall ipv4 name LOCALTOLAN default-action drop
          - set firewall ipv4 name LOCALTOLAN rule 10 action accept
          - set firewall ipv4 name LOCALTOLAN rule 10 state established
          - set firewall ipv4 name LOCALTOLAN  rule 10 state related
          - set firewall zone LAN from LOCAL firewall name LOCALTOLAN

          # VRRP
          - set high-availability vrrp group WAN vrid 10
          - set high-availability vrrp group WAN interface eth0
          - set high-availability vrrp group WAN address {{ vrrp_wan_address }}
          - set high-availability vrrp group WAN priority 150
          - set high-availability vrrp group WAN preempt-delay 5

          - set high-availability vrrp group LAN vrid 20
          - set high-availability vrrp group LAN interface eth1
          - set high-availability vrrp group LAN address {{ vrrp_lan_address }}
          - set high-availability vrrp group LAN priority 150
          - set high-availability vrrp group LAN preempt-delay 5

        save: true